package scanner;

//USATA DA SCANNER QUANDO RILEVA ERRORI DURANTE ANALISI LESSICALE 
//(SIMBOLO SCONOSCIUTO) E LANCIO ECCEZIONE

public class LexicalException extends Exception {
	
	// Costruttori
	//QUANDO VIENE CHIAMATO USO UN MESSAGGIO PREDEFINITO
	public LexicalException() {
        super("Errore lessicale non specificato."); //CHIAMA IL COSTRUTTORE DELLA CLASSE BASE (EXCEPTION IN QUESTO CASO)
        //PASSA AL COSTRUTTORE DI EXCEPTION IL MESSAGGIO "ERRORE LESSICALE NON SPECIFICATO.".
        //QUESTO MESSAGGIO DIVENTERÀ IL MESSAGGIO DELL'ECCEZIONE E POTRÀ ESSERE RECUPERATO CON IL METODO GETMESSAGE().
    }

    // Costruttore con messaggio personalizzato
    public LexicalException(String message) {
        super(message); //IL VALORE DI MESSAGE PASSATO COME ARGOMENTO AL COSTRUTTORE VIENE TRASFERITO AL COSTRUTTORE DELLA CLASSE EXCEPTION.
    }
}
